import Head from 'next/head';
import Image from 'next/image';
import { useState } from 'react';
import Spinner from 'react-spinners/MoonLoader';

import Form from '../components/Form';

export default function Home() {
  const [imgUrl, setImgUrl] = useState('');
  const [isLoading, setIsLoading] = useState(false);

  return (
    <div>
      <Head>
        <title>OpenAI Generate Image</title>
        <meta content="Generated by create next app" name="description" />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <main>
        <section className="showcase">
          <Form isImageLoading={setIsLoading} setImg={setImgUrl} />
        </section>

        <Spinner
          color="#3A646C"
          cssOverride={{
            display: 'block',
            margin: '100px auto',
          }}
          loading={isLoading}
          size={150}
        />

        {imgUrl && (
          <section className="image">
            <div className="image-container">
              <h2 className="msg">Here's your image!</h2>
              <Image
                alt=""
                height={400}
                id="image"
                loading="lazy"
                src={imgUrl}
                width={400}
              />
            </div>
          </section>
        )}
      </main>
    </div>
  );
}
